import { expect, test } from "@playwright/test";
test('delivery dependency editor shows cycles and preserves lag',async({page})=>{
 const {token}=await(await page.request.post('/__e2e/invite?org=a')).json();await page.goto(`/#token=${token}`);await page.getByLabel('New project').fill('Delivery sequences');await page.getByRole('button',{name:'Create project',exact:true}).click();await page.getByRole('button',{name:'Delivery',exact:true}).click();
 for(const title of ['First activity','Second activity']){await page.getByRole('button',{name:'Add delivery record',exact:true}).click();await page.getByLabel('Record type',{exact:true}).selectOption('activity');await page.getByLabel('Record title',{exact:true}).fill(title);await page.getByRole('button',{name:'Save delivery record',exact:true}).click();await expect(page.getByRole('button',{name:'Edit delivery record',exact:true})).toBeVisible();}
 await page.getByLabel('Predecessor',{exact:true}).selectOption({label:'First activity'});await page.getByLabel('Lag in calendar days').fill('3');await page.getByRole('button',{name:'Save dependency',exact:true}).click();await expect(page.getByText(/First activity · 3 day lag/)).toBeVisible();
 await page.getByRole('button',{name:/First activity.*activity/}).click();await page.getByLabel('Predecessor',{exact:true}).selectOption({label:'Second activity'});await page.getByRole('button',{name:'Save dependency',exact:true}).click();await expect(page.getByRole('alert')).toContainText('dependency cycle');await expect(page.getByLabel('Predecessor',{exact:true})).not.toHaveValue('');
});
test('work split creates children and retires unused child',async({page})=>{
 const {token}=await(await page.request.post('/__e2e/invite?org=a')).json();await page.goto(`/#token=${token}`);await page.getByLabel('New project').fill('Work split controls');await page.getByRole('button',{name:'Create project',exact:true}).click();await expect(page.getByRole('button',{name:'Works',exact:true})).toBeVisible();const project=new URL(page.url()).pathname.split('/').pop();const profile=await(await page.request.get(`/api/projects/${project}/profile`)).json();
 await page.request.post(`/api/projects/${project}/works`,{headers:{Origin:'http://127.0.0.1:4173'},data:{part_id:profile.parts[0].id,system_id:'hydraulic.gas',action:'new',title:'Gas work'}});
 await page.getByRole('button',{name:'Works',exact:true}).click();await page.getByRole('button',{name:/Gas work/}).click();await page.getByRole('button',{name:'Split work item',exact:true}).click();await page.getByLabel('Child 1 title').fill('Gas branch one');await page.getByLabel('Child 2 title').fill('Gas branch two');await page.getByRole('button',{name:'Save work split',exact:true}).click();await page.getByRole('button',{name:/Gas branch one/}).click();await page.getByRole('button',{name:'Retire work item',exact:true}).click();await page.getByRole('button',{name:'Confirm retirement',exact:true}).click();await expect(page.getByRole('button',{name:/Gas branch one/})).toHaveCount(0);await expect(page.getByRole('button',{name:/Gas branch two/})).toBeVisible();
});

test('summary and systems retain filing and roll back failed optimistic scope within the feedback budget',async({page})=>{
 const {token}=await(await page.request.post('/__e2e/invite?org=a')).json();await page.goto(`/#token=${token}`);await page.getByLabel('New project').fill('Profile view controls');await page.getByRole('button',{name:'Create project',exact:true}).click();await page.getByRole('button',{name:'Summary',exact:true}).click();await expect(page.getByRole('heading',{name:'Project',exact:true})).toBeVisible();await expect(page.getByRole('region',{name:'Cost summary',exact:true})).toContainText('Unknown');await expect(page.getByRole('region',{name:'Scope of works',exact:true})).toBeHidden();await expect(page.getByRole('complementary',{name:'Document register',exact:true})).toBeHidden();
 await page.getByRole('button',{name:'Systems',exact:true}).click();const toggle=page.locator('.pf-scope-group summary input').first();await expect(toggle).toBeVisible();const was=await toggle.isChecked();let release!:()=>void;const blocked=new Promise<void>(resolve=>{release=resolve;});await page.route('**/profile/scope',async route=>{await blocked;await route.fulfill({status:409,body:'Scope changed'});});
 const feedback=await toggle.evaluate(async (element: HTMLInputElement)=>{const before=performance.now();element.click();await new Promise(requestAnimationFrame);return {elapsed:performance.now()-before,checked:element.checked};});expect(feedback.checked).toBe(!was);expect(feedback.elapsed).toBeLessThan(100);release();await expect(page.getByRole('alert')).toContainText('Scope changed');await expect(toggle).toBeChecked({checked:was});await page.getByRole('button',{name:'Filing',exact:true}).click();await expect(page.getByRole('complementary',{name:'Document register',exact:true})).toBeVisible();
});
