import { expect, test } from "@playwright/test";

test("failed delivery loading remains unavailable until retry succeeds", async ({ page }) => {
  const { token } = await (await page.request.post("/__e2e/invite?org=a")).json();
  await page.goto(`/#token=${token}`);
  await page.getByLabel("New project").fill("Synthetic delivery recovery");
  await page.getByRole("button", { name: "Create project", exact: true }).click();
  await expect(page.getByRole("button", { name: "Delivery", exact: true })).toBeVisible();
  let unavailable = true;
  await page.route("**/api/projects/*/delivery", route => unavailable ? route.fulfill({ status: 500, body: "unavailable" }) : route.continue());
  await page.getByRole("button", { name: "Delivery", exact: true }).click();
  await expect(page.getByText("Delivery records unavailable.", { exact: true })).toBeVisible();
  await expect(page.getByText(/No delivery records yet/)).not.toBeVisible();
  await expect(page.getByRole("button", { name: "Add delivery record", exact: true })).toBeDisabled();
  await page.setViewportSize({ width: 1360, height: 1000 });
  await page.screenshot({ path: "../.tools/wp35-delivery-load-error.png", fullPage: true });
  unavailable = false;
  await page.getByRole("button", { name: "Reload saved delivery records", exact: true }).click();
  await expect(page.getByRole("button", { name: "Add delivery record", exact: true })).toBeEnabled();
  await expect(page.getByText(/No delivery records yet/)).toBeVisible();
  await expect(page.getByRole("alert")).not.toBeVisible();
  await page.screenshot({ path: "../.tools/wp35-delivery-load-recovered.png", fullPage: true });
});

test("delivery entries preserve unknown dates and reconcile edits before appearing in an RFP", async ({ page }) => {
  const { token } = await (await page.request.post("/__e2e/invite?org=a")).json();
  await page.goto(`/#token=${token}`);
  await page.getByLabel("New project").fill("Synthetic delivery review");
  await page.getByRole("button", { name: "Create project", exact: true }).click();
  await expect(page.getByRole("button", { name: "Delivery", exact: true })).toBeVisible();
  const project = new URL(page.url()).pathname.split("/").pop();
  const headers = { Origin: "http://127.0.0.1:4173" };
  const pkgResponse = await page.request.post(`/api/projects/${project}/packages`, { headers, data: { kind: "services", title: "Synthetic fire engineering" } });
  expect(pkgResponse.ok()).toBeTruthy();
  const pkg = await pkgResponse.json();
  const base = `/api/projects/${project}/delivery`;
  await page.getByRole("button", { name: "Delivery", exact: true }).click();
  await expect(page.getByText(/No delivery records yet/)).toBeVisible();
  await page.getByRole("button", { name: "Add delivery record", exact: true }).click();
  await page.getByLabel("Record type", { exact: true }).selectOption("approval");
  await page.getByLabel("Record title", { exact: true }).fill("Synthetic fire strategy approval");
  await page.getByLabel("Owner name or role", { exact: true }).fill("Project manager");
  await page.getByLabel("Package", { exact: true }).selectOption(pkg.id);
  await page.getByLabel("Target date", { exact: true }).fill("2026-12-01");
  await page.getByLabel("Approval authority", { exact: true }).fill("Synthetic authority");
  await page.getByRole("button", { name: "Save delivery record", exact: true }).click();
  await expect(page.getByRole("button", { name: "Edit delivery record", exact: true })).toBeVisible();
  let saved = (await (await page.request.get(base)).json()).items[0];
  expect(saved.status).toBe("not_submitted");
  expect(saved.actual_date).toBeNull();
  expect(saved.review_status).toBe("accepted_for_planning");
  await page.getByRole("button", { name: "Edit delivery record", exact: true }).click();
  await page.getByLabel("Approval reference", { exact: true }).fill("SYN-42");
  await page.getByLabel("Target date", { exact: true }).fill("");
  await page.getByRole("button", { name: "Reports", exact: true }).click();
  await page.getByRole("button", { name: "Delivery", exact: true }).click();
  await expect(page.getByLabel("Approval reference", { exact: true })).toHaveValue("SYN-42");
  const changed = await page.request.patch(`${base}/${saved.id}`, { headers, data: { version: saved.version, status: "submitted", details: { authority: "Updated synthetic authority", reference: "", submitted_on: "2026-10-05" } } });
  expect(changed.ok()).toBeTruthy();
  await expect(page.getByText("Saved delivery record changed", { exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Save delivery record", exact: true })).toBeDisabled();
  await page.setViewportSize({ width: 1360, height: 1000 });
  await page.screenshot({ path: "../.tools/wp35-delivery-editor-desktop.png", fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: "../.tools/wp35-delivery-editor-mobile.png", fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.getByRole("button", { name: "Keep my edits against this version", exact: true }).click();
  await expect(page.getByLabel("Approval authority", { exact: true })).toHaveValue("Updated synthetic authority");
  await expect(page.getByLabel("Approval reference", { exact: true })).toHaveValue("SYN-42");
  await expect(page.getByLabel("Status", { exact: true })).toHaveValue("submitted");
  await page.getByRole("button", { name: "Save delivery record", exact: true }).click();
  await expect(page.getByRole("button", { name: "Edit delivery record", exact: true })).toBeVisible();
  saved = (await (await page.request.get(base)).json()).items[0];
  expect(saved.target_date).toBeNull();
  expect(saved.details.reference).toBe("SYN-42");
  expect(saved.details.submitted_on).toBe("2026-10-05");
  expect(saved.status).toBe("submitted");
  await page.getByRole("button", { name: "Add delivery record", exact: true }).click();
  await page.getByLabel("Record type", { exact: true }).selectOption("risk");
  await page.getByLabel("Record title", { exact: true }).fill("Synthetic access constraint");
  await page.getByLabel("Likelihood", { exact: true }).fill("Awaiting site review");
  await page.getByLabel("Consequence", { exact: true }).fill("Access may delay the proposed investigation.");
  await page.getByRole("button", { name: "Save delivery record", exact: true }).click();
  await expect(page.getByRole("button", { name: "Edit delivery record", exact: true })).toBeVisible();
  await page.getByRole("button", { name: /Synthetic fire strategy approval/ }).click();
  await page.setViewportSize({ width: 1360, height: 1000 });
  await page.screenshot({ path: "../.tools/wp35-delivery-desktop.png", fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: "../.tools/wp35-delivery-mobile.png", fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  const createdReport = await page.request.post(`/api/projects/${project}/reports`, { headers, data: { kind: "rfp", package_id: pkg.id } });
  expect(createdReport.ok()).toBeTruthy();
  const report = await createdReport.json();
  const draft = await page.request.post(`/api/reports/${report.id}/draft`, { headers, data: { use_last_completed: true } });
  expect(draft.ok()).toBeTruthy();
  const text = JSON.stringify(await draft.json());
  expect(text).toContain("Synthetic fire strategy approval");
  expect(text).toContain("Synthetic access constraint");
});
