import { expect, test } from "@playwright/test";
test('PMP issue preserves stated stale reason, downloads and immutable history',async({page})=>{
 page.on('pageerror',error=>{throw error;});
 const {token}=await(await page.request.post('/__e2e/invite?org=a')).json();await page.goto(`/#token=${token}`);await page.getByLabel('New project').fill('PMP issue controls');await page.getByRole('button',{name:'Create project',exact:true}).click();await page.getByRole('button',{name:'Reports',exact:true}).click();await page.getByLabel('Report type',{exact:true}).selectOption('pmp');await page.getByRole('button',{name:'Create PMP draft',exact:true}).click();await page.getByRole('button',{name:'Assemble draft',exact:true}).click();await expect(page.getByRole('button',{name:'Issue report',exact:true})).toBeVisible();
 const project=new URL(page.url()).pathname.split('/').pop();const headers={Origin:'http://127.0.0.1:4173'};await page.request.post(`/api/projects/${project}/delivery`,{headers,data:{kind:'milestone',title:'New milestone after draft',target_date:'2026-10-08',forecast_date:'2026-10-10'}});await expect(page.getByText('Delivery records changed',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Issue report',exact:true}).click();await page.getByLabel('Reporting date',{exact:true}).fill('2026-10-07');await expect(page.getByRole('button',{name:'Freeze and issue PDF',exact:true})).toBeDisabled();await page.getByLabel('Issue the saved state despite changed or incomplete sources').check();await page.getByLabel('Reason for using saved state').fill('Issue the agreed scope before incorporating the new milestone.');
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'../.tools/next-wave-issue-mobile.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
 await page.getByRole('button',{name:'Freeze and issue PDF',exact:true}).click();const link=page.getByRole('link',{name:/Download issue 1/});await expect(link).toBeVisible();const download=await page.request.get((await link.getAttribute('href'))!);expect(download.headers()['content-type']).toContain('application/pdf');expect((await download.body()).subarray(0,5).toString()).toBe('%PDF-');
 await page.getByRole('button',{name:'Assemble draft',exact:true}).click();await expect(page.getByRole('table')).toContainText('2 days later');await expect(page.getByRole('columnheader',{name:'Target',exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await expect(link).toBeVisible();await page.getByRole('button',{name:'Issue report',exact:true}).click();if(await page.getByLabel('Issue the saved state despite changed or incomplete sources').count()){await page.getByLabel('Issue the saved state despite changed or incomplete sources').check();await page.getByLabel('Reason for using saved state').fill('Test readable page limit with saved sources.');}await page.route('**/api/reports/*/issue',route=>route.fulfill({status:422,contentType:'application/json',body:JSON.stringify({error:'report_overflow'})}));await page.getByRole('button',{name:'Freeze and issue PDF',exact:true}).click();await expect(page.getByRole('alert')).toContainText('exceeds two readable pages');await expect(page.getByRole('link',{name:/Download issue 2/})).toHaveCount(0);
});
