import { expect, test } from "@playwright/test";

test("saved report creation, citations, protected edit, refresh and mobile reading", async ({ page }) => {
  const invite = await page.request.post("/__e2e/invite?org=a");
  const { token } = await invite.json();
  await page.goto(`/#token=${token}`);
  await page.getByLabel("New project").fill("Report review regression");
  await page.getByRole("button", { name: "Create project", exact: true }).click();
  await expect(page.getByRole("button", { name: "Reports", exact: true })).toBeVisible();
  const project = new URL(page.url()).pathname.split("/").pop();
  await page.getByRole("button", { name: "Packages", exact: true }).click();
  await page.getByLabel("Package title", { exact: true }).fill("Fire engineering");
  await page.getByLabel("Separate stages before and after novation").check();
  await page.getByRole("button", { name: "Create package", exact: true }).click();
  await page.getByLabel("Scope wording", { exact: true }).fill("Review fire strategy and identify required investigations.");
  await page.getByLabel("Deliverable", { exact: true }).fill("Fire strategy report");
  await page.getByRole("button", { name: "Add scope item", exact: true }).click();
  await expect(page.locator(".report-block .report-wording")).toHaveText("Review fire strategy and identify required investigations.");
  const packages = await (await page.request.get(`/api/projects/${project}/packages`)).json();
  const pkg = packages.items[0];
  expect(pkg.novation).toBe(true);
  const profile = await (await page.request.get(`/api/projects/${project}/profile`)).json();
  const work = await page.request.post(`/api/projects/${project}/works`, { headers: { Origin: "http://127.0.0.1:4173" }, data: { part_id: profile.parts[0].id, system_id: "hydraulic.gas", action: "new", title: "Gas service" } });
  expect(work.ok()).toBeTruthy();
  await page.getByLabel("Scope type", { exact: true }).selectOption("responsibility");
  await page.getByLabel("Work item", { exact: true }).selectOption({ label: "Gas service · new · included" });
  await page.getByLabel("Responsibility", { exact: true }).selectOption("design");
  await page.getByLabel("Stage", { exact: true }).selectOption(pkg.stages[0].id);
  await page.getByLabel("Scope wording", { exact: true }).fill("Design the gas service.");
  await page.getByRole("button", { name: "Add scope item", exact: true }).click();
  await expect(page.getByText("Work: Gas service · design", { exact: true })).toBeVisible();
  await expect(page.getByText(`Stage: ${pkg.stages[0].label} · before novation`, { exact: true })).toBeVisible();
  const packageRegion = page.getByRole("region", { name: "Packages", exact: true });
  await packageRegion.locator(".." ).evaluate(el => { el.scrollTop = 0; });
  await page.screenshot({ path: "../.tools/wp45-packages-desktop.png", fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: "../.tools/wp45-packages-mobile.png", fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  await page.setViewportSize({ width: 1280, height: 720 });
  await page.getByRole("button", { name: "Reports", exact: true }).click();
  await page.getByRole("button", { name: "Create RFP draft", exact: true }).click();
	let incomplete = true;
	await page.route("**/api/reports/*/draft", async route => {
	  if (incomplete) { incomplete = false; expect(route.request().postDataJSON().use_last_completed).toBe(false); await route.fulfill({ status: 409, json: { error: "reading_incomplete" } }); }
	  else { expect(route.request().postDataJSON().use_last_completed).toBe(true); await route.continue(); }
	});
  await page.getByRole("button", { name: "Assemble draft", exact: true }).click();
	await expect(page.getByText("Document reading is incomplete", { exact: true })).toBeVisible();
	await page.getByRole("button", { name: "Use last completed state", exact: true }).click();
	await page.unroute("**/api/reports/*/draft");
  await expect(page.getByRole("heading", { name: "Stages, services and deliverables", exact: true })).toBeVisible();
  await expect(page.getByText("included. Review fire strategy and identify required investigations.. Deliverable: Fire strategy report", { exact: true })).toBeVisible();
  const packageBlock = page.locator(".report-block").filter({ has: page.getByRole("heading", { name: "Package", exact: true }) });
  await packageBlock.getByRole("button", { name: "Edit wording: Package", exact: true }).click();
  await page.getByLabel("Report wording").fill("Protect this appointment wording.");
  await page.getByRole("button", { name: "Save wording", exact: true }).click();
  await expect(packageBlock.locator(".report-wording")).toHaveText("Protect this appointment wording.");
  await expect(packageBlock.locator("summary")).toHaveCount(2);
  await packageBlock.locator("summary").last().click();
  await expect(packageBlock.getByText("User wording by", { exact: false })).toBeVisible();
  const change = await page.request.patch(`/api/projects/${project}/packages/${pkg.id}`, { headers: { Origin: "http://127.0.0.1:4173" }, data: { version: pkg.version, title: "Revised fire engineering" } });
  expect(change.ok()).toBeTruthy();
  await page.getByRole("button", { name: "Refresh draft", exact: true }).click();
  await expect(packageBlock.getByText("The source changed.", { exact: false })).toBeVisible();
  await expect(packageBlock.getByText("Protect this appointment wording.", { exact: true })).toBeVisible();
  await packageBlock.getByRole("button", { name: "Edit wording: Package", exact: true }).click();
  await page.getByLabel("Report wording").fill("My unsaved reconciliation.");
  const list = await (await page.request.get(`/api/projects/${project}/reports`)).json();
  const reportId = list[0].id;
  const current = await (await page.request.get(`/api/reports/${reportId}`)).json();
  const otherEdit = await page.request.put(`/api/reports/${reportId}/edits/${encodeURIComponent(`package:${pkg.id}`)}`, { headers: { Origin: "http://127.0.0.1:4173" }, data: { version: current.draft.version, text: "Another editor's wording." } });
  expect(otherEdit.ok()).toBeTruthy();
  await page.getByRole("button", { name: "Save wording", exact: true }).click();
  await page.getByRole("button", { name: "Review latest draft", exact: true }).click();
  await expect(page.getByLabel("Review concurrent edit").getByText("Another editor's wording.", { exact: true })).toBeVisible();
  await expect(page.getByLabel("Report wording")).toHaveValue("My unsaved reconciliation.");
  await page.screenshot({ path: "../.tools/wp45-reports-conflict.png", fullPage: true });
  await page.getByRole("button", { name: "Keep my wording against this version", exact: true }).click();
  await page.getByRole("button", { name: "Save wording", exact: true }).click();
  await expect(packageBlock.locator(".report-wording")).toHaveText("My unsaved reconciliation.");
  await page.screenshot({ path: "../.tools/wp45-reports-desktop.png", fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: "../.tools/wp45-reports-mobile.png", fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  await page.reload();
  await page.getByRole("button", { name: "Reports", exact: true }).click();
  await page.getByRole("button", { name: "RFP — Fire engineering", exact: true }).click();
  await expect(page.getByText("My unsaved reconciliation.", { exact: true })).toBeVisible();
	const restoredBlock = page.locator(".report-block").filter({ has: page.getByRole("heading", { name: "Package", exact: true }) });
	await restoredBlock.getByRole("button", { name: "Restore saved source wording", exact: true }).click();
	await page.getByRole("dialog").getByRole("button", { name: "Cancel", exact: true }).click();
	await expect(restoredBlock.locator(".report-wording")).toHaveText("My unsaved reconciliation.");
	await restoredBlock.getByRole("button", { name: "Restore saved source wording", exact: true }).click();
	await page.getByRole("dialog").getByRole("button", { name: "Restore wording", exact: true }).click();
	await expect(restoredBlock.locator(".report-wording")).toHaveText("Revised fire engineering — planned");
	await expect(restoredBlock.getByText("Protected wording", { exact: true })).toHaveCount(0);
});
