import { expect, test } from "@playwright/test";

test("work corrections retain targets, survive navigation and reconcile concurrent edits", async ({ page }) => {
  const { token } = await (await page.request.post("/__e2e/invite?org=a")).json();
  await page.goto(`/#token=${token}`);
  await page.getByLabel("New project").fill("Synthetic work review");
  await page.getByRole("button", { name: "Create project", exact: true }).click();
  await expect(page.getByRole("button", { name: "Works", exact: true })).toBeVisible();
  const project = new URL(page.url()).pathname.split("/").pop();
  const profile = await (await page.request.get(`/api/projects/${project}/profile`)).json();
  const base = `/api/projects/${project}/works`;
  const headers = { Origin: "http://127.0.0.1:4173" };
  const response = await page.request.post(base, { headers, data: { part_id: profile.parts[0].id, system_id: "hydraulic.gas", action: "investigate", title: "Synthetic gas service", target: { text: "Confirm condition", values: [{ key: "plan.gross_floor_area", value: 100, unit: "m2" }] } } });
  expect(response.ok()).toBeTruthy();
  const created = await response.json();
  await page.getByRole("button", { name: "Works", exact: true }).click();
  await page.getByRole("button", { name: /Synthetic gas service/ }).click();
  await page.getByRole("button", { name: "Correct work item", exact: true }).click();
  await page.getByLabel("Action", { exact: true }).selectOption("repair");
  await page.getByLabel("Target wording", { exact: true }).fill("Repair and test the existing connection.");
  await page.getByLabel("Planning quantity", { exact: true }).fill("12.50");
  await page.getByLabel("Unit", { exact: true }).fill("m");
  await page.getByRole("button", { name: "Packages", exact: true }).click();
  await page.getByRole("button", { name: "Works", exact: true }).click();
  await expect(page.getByLabel("Target wording", { exact: true })).toHaveValue("Repair and test the existing connection.");
  const concurrent = await page.request.patch(`${base}/${created.id}`, { headers, data: { version: created.version, title: "Updated synthetic service", target: { text: "Another reviewer's target", values: [{ key: "plan.gross_floor_area", value: 200, unit: "m2" }] } } });
  expect(concurrent.ok()).toBeTruthy();
  await expect(page.getByText("Saved work changed", { exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Save correction", exact: true })).toBeDisabled();
  await expect(page.getByRole("region", { name: "Saved work", exact: true })).toContainText("Another reviewer's target");
  await expect(page.getByLabel("Target wording", { exact: true })).toHaveValue("Repair and test the existing connection.");
  await page.getByRole("region", { name: "Works", exact: true }).locator("..").evaluate(el => { el.scrollTop = 0; });
  await page.screenshot({ path: "../.tools/wp45-works-desktop.png", fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: "../.tools/wp45-works-mobile.png", fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.getByRole("button", { name: "Keep my correction against this version", exact: true }).click();
  await page.getByRole("button", { name: "Save correction", exact: true }).click();
  await expect(page.getByRole("button", { name: "Correct work item", exact: true })).toBeVisible();
  const saved = (await (await page.request.get(base)).json()).items[0];
  expect(saved.action).toBe("repair");
  expect(saved.target.text).toBe("Repair and test the existing connection.");
  expect(saved.target.values[0].value).toBe(200);
  expect(saved.quantity).toBe("12.50");
  expect(saved.version).toBe(3);
  await page.getByRole("button", { name: "Correct work item", exact: true }).click();
  await page.getByLabel("Planning quantity", { exact: true }).fill("");
  await page.getByRole("button", { name: "Save correction", exact: true }).click();
  await expect(page.getByText("Quantity: Not recorded", { exact: true })).toBeVisible();
});
