// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: decisions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const correctFilingDecision = `-- name: CorrectFilingDecision :execrows
INSERT INTO decisions (
    org_id, id, document_id, field, value, band, decided_by, question_version, confidence, version
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4,
    $5,
    'green',
    'user',
    NULL,
    NULL,
    1
)
ON CONFLICT (org_id, document_id, field) DO UPDATE
SET
    value = EXCLUDED.value,
    band = 'green',
    decided_by = 'user',
    question_version = NULL,
    confidence = NULL,
    version = decisions.version + 1
`

type CorrectFilingDecisionParams struct {
	OrgID      string
	ID         string
	DocumentID string
	Field      string
	Value      *string
}

func (q *Queries) CorrectFilingDecision(ctx context.Context, arg CorrectFilingDecisionParams) (int64, error) {
	result, err := q.db.Exec(ctx, correctFilingDecision,
		arg.OrgID,
		arg.ID,
		arg.DocumentID,
		arg.Field,
		arg.Value,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishIntakeJob = `-- name: FinishIntakeJob :execrows
UPDATE jobs
SET status = 'done'
WHERE org_id = $1::uuid
  AND document_id = $2::uuid
  AND kind = 'intake'
`

type FinishIntakeJobParams struct {
	OrgID      string
	DocumentID string
}

func (q *Queries) FinishIntakeJob(ctx context.Context, arg FinishIntakeJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishIntakeJob, arg.OrgID, arg.DocumentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertScopedSupersession = `-- name: InsertScopedSupersession :execrows
INSERT INTO supersessions (org_id, document_id, prior_document_id)
SELECT $1::uuid, $2::uuid, $3::uuid
WHERE $2::uuid <> $3::uuid
  AND EXISTS (
    SELECT 1
    FROM documents newer
    JOIN documents prior
        ON prior.org_id = newer.org_id
       AND prior.project_id = newer.project_id
       AND prior.identity_page = newer.identity_page
       AND upper(prior.document_number) = upper(newer.document_number)
       AND prior.document_number IS NOT NULL
       AND prior.id <> newer.id
    WHERE newer.org_id = $1::uuid
      AND newer.id = $2::uuid
      AND prior.id = $3::uuid
  )
`

type InsertScopedSupersessionParams struct {
	OrgID           string
	DocumentID      string
	PriorDocumentID string
}

func (q *Queries) InsertScopedSupersession(ctx context.Context, arg InsertScopedSupersessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertScopedSupersession, arg.OrgID, arg.DocumentID, arg.PriorDocumentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listFilingDecisions = `-- name: ListFilingDecisions :many
SELECT
    field,
    COALESCE(value, '') AS value,
    band,
    decided_by,
    COALESCE(question_version, '') AS question_version,
    confidence,
    version
FROM decisions
WHERE org_id = $1::uuid
  AND document_id = $2::uuid
ORDER BY field
`

type ListFilingDecisionsParams struct {
	OrgID      string
	DocumentID string
}

type ListFilingDecisionsRow struct {
	Field           string
	Value           string
	Band            string
	DecidedBy       string
	QuestionVersion string
	Confidence      pgtype.Float8
	Version         int64
}

func (q *Queries) ListFilingDecisions(ctx context.Context, arg ListFilingDecisionsParams) ([]ListFilingDecisionsRow, error) {
	rows, err := q.db.Query(ctx, listFilingDecisions, arg.OrgID, arg.DocumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFilingDecisionsRow
	for rows.Next() {
		var i ListFilingDecisionsRow
		if err := rows.Scan(
			&i.Field,
			&i.Value,
			&i.Band,
			&i.DecidedBy,
			&i.QuestionVersion,
			&i.Confidence,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgSupersessions = `-- name: ListOrgSupersessions :many
SELECT
    document_id::text AS document_id,
    prior_document_id::text AS prior_document_id
FROM supersessions
WHERE org_id = $1::uuid
`

type ListOrgSupersessionsRow struct {
	DocumentID      string
	PriorDocumentID string
}

func (q *Queries) ListOrgSupersessions(ctx context.Context, orgID string) ([]ListOrgSupersessionsRow, error) {
	rows, err := q.db.Query(ctx, listOrgSupersessions, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgSupersessionsRow
	for rows.Next() {
		var i ListOrgSupersessionsRow
		if err := rows.Scan(&i.DocumentID, &i.PriorDocumentID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectDocuments = `-- name: ListProjectDocuments :many
SELECT
    id::text AS id,
    project_id::text AS project_id,
    COALESCE(document_number, '') AS document_number,
    COALESCE(revision, '') AS revision,
    status
FROM documents
WHERE org_id = $1::uuid
  AND project_id = $2::uuid
ORDER BY id
`

type ListProjectDocumentsParams struct {
	OrgID     string
	ProjectID string
}

type ListProjectDocumentsRow struct {
	ID             string
	ProjectID      string
	DocumentNumber string
	Revision       string
	Status         string
}

func (q *Queries) ListProjectDocuments(ctx context.Context, arg ListProjectDocumentsParams) ([]ListProjectDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listProjectDocuments, arg.OrgID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectDocumentsRow
	for rows.Next() {
		var i ListProjectDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.DocumentNumber,
			&i.Revision,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockFilingDocument = `-- name: LockFilingDocument :one
SELECT
    id::text AS id,
    project_id::text AS project_id,
    filename,
    status,
    COALESCE(document_number, '') AS document_number,
    COALESCE(revision, '') AS revision
FROM documents
WHERE org_id = $1::uuid
  AND id = $2::uuid
FOR UPDATE
`

type LockFilingDocumentParams struct {
	OrgID string
	ID    string
}

type LockFilingDocumentRow struct {
	ID             string
	ProjectID      string
	Filename       string
	Status         string
	DocumentNumber string
	Revision       string
}

func (q *Queries) LockFilingDocument(ctx context.Context, arg LockFilingDocumentParams) (LockFilingDocumentRow, error) {
	row := q.db.QueryRow(ctx, lockFilingDocument, arg.OrgID, arg.ID)
	var i LockFilingDocumentRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Filename,
		&i.Status,
		&i.DocumentNumber,
		&i.Revision,
	)
	return i, err
}

const setFiledIdentity = `-- name: SetFiledIdentity :execrows
UPDATE documents
SET
    status = 'filed',
    document_number = $1,
    revision = $2
WHERE org_id = $3::uuid
  AND id = $4::uuid
  AND status = 'pending'
`

type SetFiledIdentityParams struct {
	DocumentNumber *string
	Revision       *string
	OrgID          string
	ID             string
}

func (q *Queries) SetFiledIdentity(ctx context.Context, arg SetFiledIdentityParams) (int64, error) {
	result, err := q.db.Exec(ctx, setFiledIdentity,
		arg.DocumentNumber,
		arg.Revision,
		arg.OrgID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertFilingDecision = `-- name: UpsertFilingDecision :execrows
INSERT INTO decisions (
    org_id, id, document_id, field, value, band, decided_by, question_version, confidence, version
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4,
    $5,
    $6,
    $7,
    $8,
    CASE
        WHEN $9::boolean THEN $10::float8
        ELSE NULL
    END,
    1
)
ON CONFLICT (org_id, document_id, field) DO UPDATE
SET
    value = EXCLUDED.value,
    band = EXCLUDED.band,
    decided_by = EXCLUDED.decided_by,
    question_version = EXCLUDED.question_version,
    confidence = EXCLUDED.confidence,
    version = decisions.version + 1
WHERE decisions.decided_by <> 'user'
  AND decisions.version = $11
`

type UpsertFilingDecisionParams struct {
	OrgID           string
	ID              string
	DocumentID      string
	Field           string
	Value           *string
	Band            string
	DecidedBy       string
	QuestionVersion *string
	ConfidenceSet   bool
	Confidence      float64
	ExpectedVersion int64
}

func (q *Queries) UpsertFilingDecision(ctx context.Context, arg UpsertFilingDecisionParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertFilingDecision,
		arg.OrgID,
		arg.ID,
		arg.DocumentID,
		arg.Field,
		arg.Value,
		arg.Band,
		arg.DecidedBy,
		arg.QuestionVersion,
		arg.ConfidenceSet,
		arg.Confidence,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
