// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Decision struct {
	OrgID           string
	ID              string
	DocumentID      string
	Field           string
	Value           *string
	Band            string
	DecidedBy       string
	QuestionVersion *string
	Confidence      pgtype.Float8
	Version         int64
	CreatedAt       time.Time
}

type Document struct {
	OrgID          string
	ID             string
	ProjectID      string
	FileID         string
	Filename       string
	Status         string
	DocumentNumber *string
	Revision       *string
	CreatedAt      time.Time
}

type File struct {
	OrgID     string
	ID        string
	ProjectID string
	Sha256    []byte
	ByteSize  int64
	MediaType string
	CreatedAt time.Time
}

type Invite struct {
	OrgID      string
	ID         string
	Email      string
	TokenHash  []byte
	ExpiresAt  time.Time
	ConsumedAt pgtype.Timestamptz
	Role       string
}

type Job struct {
	OrgID       string
	ID          string
	DocumentID  string
	Kind        string
	Status      string
	Attempts    int32
	RunAfter    time.Time
	LockedUntil pgtype.Timestamptz
	CreatedAt   time.Time
}

type Membership struct {
	OrgID     string
	UserID    string
	Role      string
	CreatedAt time.Time
}

type Org struct {
	ID        string
	Name      string
	CreatedAt time.Time
}

type Passage struct {
	OrgID      string
	ID         string
	DocumentID string
	Ordinal    int32
	Body       string
	CreatedAt  time.Time
}

type Project struct {
	OrgID     string
	ID        string
	Name      string
	CreatedAt time.Time
}

type Session struct {
	OrgID     string
	ID        string
	UserID    string
	CreatedAt time.Time
	ExpiresAt time.Time
}

type Supersession struct {
	OrgID           string
	DocumentID      string
	PriorDocumentID string
	CreatedAt       time.Time
}

type User struct {
	OrgID     string
	ID        string
	Email     string
	CreatedAt time.Time
}
