// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Decision struct {
	OrgID           string
	ID              string
	DocumentID      string
	Field           string
	Value           *string
	Band            string
	DecidedBy       string
	QuestionVersion *string
	Confidence      pgtype.Float8
	Version         int64
	CreatedAt       time.Time
}

type Document struct {
	OrgID          string
	ID             string
	ProjectID      string
	FileID         string
	Filename       string
	Status         string
	DocumentNumber *string
	Revision       *string
	CreatedAt      time.Time
	Reason         string
	IdentityPage   int32
}

type DrawingExpansion struct {
	OrgID     string
	SourceID  string
	PageCount int32
	Status    string
	Reason    string
}

type DrawingSheet struct {
	OrgID      string
	SourceID   string
	PageNumber int32
	DocumentID string
}

type Event struct {
	OrgID      string
	ID         int64
	Kind       string
	DocumentID pgtype.UUID
	Payload    string
	CreatedAt  time.Time
}

type EventCounter struct {
	OrgID  string
	LastID int64
}

type File struct {
	OrgID     string
	ID        string
	ProjectID string
	Sha256    []byte
	ByteSize  int64
	MediaType string
	CreatedAt time.Time
}

type Invite struct {
	OrgID      string
	ID         string
	Email      string
	TokenHash  []byte
	ExpiresAt  time.Time
	ConsumedAt pgtype.Timestamptz
	Role       string
}

type Job struct {
	OrgID       string
	ID          string
	DocumentID  string
	Kind        string
	Status      string
	Attempts    int32
	RunAfter    time.Time
	LockedUntil pgtype.Timestamptz
	CreatedAt   time.Time
	Priority    int32
	LeaseToken  pgtype.UUID
	MaxAttempts int32
	LastError   string
}

type Membership struct {
	OrgID     string
	UserID    string
	Role      string
	CreatedAt time.Time
}

type Org struct {
	ID        string
	Name      string
	CreatedAt time.Time
}

type Passage struct {
	OrgID      string
	ID         string
	DocumentID string
	Ordinal    int32
	Body       string
	CreatedAt  time.Time
	BodyTsv    interface{}
}

type PassageEvidence struct {
	OrgID      string
	PassageID  string
	QuestionID string
	State      string
}

type PassageSystem struct {
	OrgID     string
	PassageID string
	SystemID  string
}

type ProfileBuild struct {
	OrgID             string
	ProjectID         string
	BuiltAt           time.Time
	ThresholdsVersion string
}

type ProfileFact struct {
	OrgID           string
	ID              string
	ProjectID       string
	DocumentID      string
	PassageID       pgtype.UUID
	QuestionID      string
	Value           string
	Unit            string
	Basis           string
	PartLabel       string
	Excerpt         string
	Confidence      pgtype.Float8
	DecidedBy       string
	QuestionVersion string
	CreatedAt       time.Time
}

type ProfileRow struct {
	OrgID        string
	ProjectID    string
	PartID       string
	Key          string
	Value        string
	Band         string
	Assertion    string
	Note         string
	Tenders      string
	Sources      []byte
	Alternatives []byte
	Derived      []byte
}

type ProfileUserValue struct {
	OrgID     string
	ProjectID string
	PartID    string
	Key       string
	Value     *string
	Note      string
	UserID    string
	Version   int64
	UpdatedAt time.Time
}

type Project struct {
	OrgID     string
	ID        string
	Name      string
	CreatedAt time.Time
}

type ProjectPart struct {
	OrgID     string
	ID        string
	ProjectID string
	Label     string
	Kind      string
	NccClass  *string
	CreatedAt time.Time
}

type Session struct {
	OrgID     string
	ID        string
	UserID    string
	CreatedAt time.Time
	ExpiresAt time.Time
}

type Supersession struct {
	OrgID           string
	DocumentID      string
	PriorDocumentID string
	CreatedAt       time.Time
}

type User struct {
	OrgID     string
	ID        string
	Email     string
	CreatedAt time.Time
}
