// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPassage = `-- name: AddPassage :exec
INSERT INTO passages (org_id, id, document_id, ordinal, body)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4,
    $5
)
`

type AddPassageParams struct {
	OrgID      string
	ID         string
	DocumentID string
	Ordinal    int32
	Body       string
}

func (q *Queries) AddPassage(ctx context.Context, arg AddPassageParams) error {
	_, err := q.db.Exec(ctx, addPassage,
		arg.OrgID,
		arg.ID,
		arg.DocumentID,
		arg.Ordinal,
		arg.Body,
	)
	return err
}

const backlog = `-- name: Backlog :many
SELECT kind,
       count(*)::bigint AS queued,
       floor(extract(epoch FROM now() - min(created_at)) * 1000)::bigint AS oldest_ms
FROM jobs
WHERE status IN ('queued', 'leased')
GROUP BY kind
ORDER BY kind
`

type BacklogRow struct {
	Kind     string
	Queued   int64
	OldestMs int64
}

// Process-wide unfinished work for health. Counts and ages only; no row of
// any org leaves this query. Age is by the database clock.
func (q *Queries) Backlog(ctx context.Context) ([]BacklogRow, error) {
	rows, err := q.db.Query(ctx, backlog)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BacklogRow
	for rows.Next() {
		var i BacklogRow
		if err := rows.Scan(&i.Kind, &i.Queued, &i.OldestMs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimJob = `-- name: ClaimJob :one
WITH picked AS MATERIALIZED (
    SELECT c.org_id, c.id
    FROM jobs c
    WHERE c.org_id = $3::uuid
      AND c.kind = ANY($4::text[])
      AND c.kind <> 'intake'
      AND c.attempts < c.max_attempts
      AND c.run_after <= now()
      AND (
          c.status = 'queued'
          OR (c.status = 'leased' AND c.locked_until < now())
      )
    ORDER BY c.priority DESC, c.run_after, c.created_at, c.id
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE jobs AS j
SET
    status = 'leased',
    attempts = j.attempts + 1,
    lease_token = $1::uuid,
    locked_until = now() + make_interval(secs => $2::double precision),
    last_error = ''
FROM picked
WHERE j.org_id = picked.org_id
  AND j.id = picked.id
RETURNING
    j.org_id::text AS org_id,
    j.id::text AS id,
    j.document_id::text AS document_id,
    j.kind,
    j.attempts,
    j.lease_token::text AS lease_token
`

type ClaimJobParams struct {
	LeaseToken   string
	LeaseSeconds float64
	OrgID        string
	Kinds        []string
}

type ClaimJobRow struct {
	OrgID      string
	ID         string
	DocumentID string
	Kind       string
	Attempts   int32
	LeaseToken string
}

// The pick is a materialized CTE so it locks once. As a FROM subquery the
// planner rescanned it inside a nested loop, and a concurrent claimer could
// come back empty while a second job was still queued.
func (q *Queries) ClaimJob(ctx context.Context, arg ClaimJobParams) (ClaimJobRow, error) {
	row := q.db.QueryRow(ctx, claimJob,
		arg.LeaseToken,
		arg.LeaseSeconds,
		arg.OrgID,
		arg.Kinds,
	)
	var i ClaimJobRow
	err := row.Scan(
		&i.OrgID,
		&i.ID,
		&i.DocumentID,
		&i.Kind,
		&i.Attempts,
		&i.LeaseToken,
	)
	return i, err
}

const completeJob = `-- name: CompleteJob :execrows
UPDATE jobs
SET status = 'done', locked_until = NULL, lease_token = NULL
WHERE org_id = $1::uuid
  AND id = $2::uuid
  AND lease_token = $3::uuid
  AND status = 'leased'
`

type CompleteJobParams struct {
	OrgID      string
	ID         string
	LeaseToken string
}

func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeJob, arg.OrgID, arg.ID, arg.LeaseToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createDecision = `-- name: CreateDecision :exec
INSERT INTO decisions (org_id, id, document_id, field, value, band, decided_by)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4,
    $5,
    $6,
    $7
)
`

type CreateDecisionParams struct {
	OrgID      string
	ID         string
	DocumentID string
	Field      string
	Value      *string
	Band       string
	DecidedBy  string
}

func (q *Queries) CreateDecision(ctx context.Context, arg CreateDecisionParams) error {
	_, err := q.db.Exec(ctx, createDecision,
		arg.OrgID,
		arg.ID,
		arg.DocumentID,
		arg.Field,
		arg.Value,
		arg.Band,
		arg.DecidedBy,
	)
	return err
}

const createDocument = `-- name: CreateDocument :exec
INSERT INTO documents (
    org_id, id, project_id, file_id, filename, status, document_number, revision, reason
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4::uuid,
    $5,
    $6,
    $7,
    $8,
    $9
)
`

type CreateDocumentParams struct {
	OrgID          string
	ID             string
	ProjectID      string
	FileID         string
	Filename       string
	Status         string
	DocumentNumber *string
	Revision       *string
	Reason         string
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) error {
	_, err := q.db.Exec(ctx, createDocument,
		arg.OrgID,
		arg.ID,
		arg.ProjectID,
		arg.FileID,
		arg.Filename,
		arg.Status,
		arg.DocumentNumber,
		arg.Revision,
		arg.Reason,
	)
	return err
}

const createFile = `-- name: CreateFile :exec
INSERT INTO files (org_id, id, project_id, sha256, byte_size, media_type)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4,
    $5,
    $6
)
`

type CreateFileParams struct {
	OrgID     string
	ID        string
	ProjectID string
	Sha256    []byte
	ByteSize  int64
	MediaType string
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) error {
	_, err := q.db.Exec(ctx, createFile,
		arg.OrgID,
		arg.ID,
		arg.ProjectID,
		arg.Sha256,
		arg.ByteSize,
		arg.MediaType,
	)
	return err
}

const createInvite = `-- name: CreateInvite :exec
INSERT INTO invites (org_id, id, email, token_hash, role, expires_at)
VALUES (
    $1::uuid,
    $2::uuid,
    $3,
    $4,
    $5,
    $6
)
`

type CreateInviteParams struct {
	OrgID     string
	ID        string
	Email     string
	TokenHash []byte
	Role      string
	ExpiresAt time.Time
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) error {
	_, err := q.db.Exec(ctx, createInvite,
		arg.OrgID,
		arg.ID,
		arg.Email,
		arg.TokenHash,
		arg.Role,
		arg.ExpiresAt,
	)
	return err
}

const createMembership = `-- name: CreateMembership :exec
INSERT INTO memberships (org_id, user_id, role)
VALUES ($1::uuid, $2::uuid, $3)
ON CONFLICT (org_id, user_id) DO NOTHING
`

type CreateMembershipParams struct {
	OrgID  string
	UserID string
	Role   string
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) error {
	_, err := q.db.Exec(ctx, createMembership, arg.OrgID, arg.UserID, arg.Role)
	return err
}

const createOrg = `-- name: CreateOrg :exec
INSERT INTO orgs (id, name)
VALUES ($1::uuid, $2)
`

type CreateOrgParams struct {
	ID   string
	Name string
}

func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) error {
	_, err := q.db.Exec(ctx, createOrg, arg.ID, arg.Name)
	return err
}

const createProject = `-- name: CreateProject :exec
INSERT INTO projects (org_id, id, name)
VALUES ($1::uuid, $2::uuid, $3)
`

type CreateProjectParams struct {
	OrgID string
	ID    string
	Name  string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.Exec(ctx, createProject, arg.OrgID, arg.ID, arg.Name)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (org_id, id, user_id)
VALUES ($1::uuid, $2::uuid, $3::uuid)
`

type CreateSessionParams struct {
	OrgID  string
	ID     string
	UserID string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.OrgID, arg.ID, arg.UserID)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (org_id, id, email)
VALUES ($1::uuid, $2::uuid, $3)
`

type CreateUserParams struct {
	OrgID string
	ID    string
	Email string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.OrgID, arg.ID, arg.Email)
	return err
}

const deleteDocumentPassages = `-- name: DeleteDocumentPassages :exec
DELETE FROM passages
WHERE org_id = $1::uuid
  AND document_id = $2::uuid
`

type DeleteDocumentPassagesParams struct {
	OrgID      string
	DocumentID string
}

func (q *Queries) DeleteDocumentPassages(ctx context.Context, arg DeleteDocumentPassagesParams) error {
	_, err := q.db.Exec(ctx, deleteDocumentPassages, arg.OrgID, arg.DocumentID)
	return err
}

const deleteOrg = `-- name: DeleteOrg :exec
DELETE FROM orgs
WHERE id = $1::uuid
`

func (q *Queries) DeleteOrg(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteOrg, id)
	return err
}

const deletePassageEvidence = `-- name: DeletePassageEvidence :exec
DELETE FROM passage_evidence
WHERE org_id = $1::uuid
  AND passage_id = $2::uuid
`

type DeletePassageEvidenceParams struct {
	OrgID     string
	PassageID string
}

func (q *Queries) DeletePassageEvidence(ctx context.Context, arg DeletePassageEvidenceParams) error {
	_, err := q.db.Exec(ctx, deletePassageEvidence, arg.OrgID, arg.PassageID)
	return err
}

const deletePassageSystems = `-- name: DeletePassageSystems :exec
DELETE FROM passage_systems
WHERE org_id = $1::uuid
  AND passage_id = $2::uuid
`

type DeletePassageSystemsParams struct {
	OrgID     string
	PassageID string
}

func (q *Queries) DeletePassageSystems(ctx context.Context, arg DeletePassageSystemsParams) error {
	_, err := q.db.Exec(ctx, deletePassageSystems, arg.OrgID, arg.PassageID)
	return err
}

const documentByFile = `-- name: DocumentByFile :one
SELECT
    d.id::text AS id,
    d.project_id::text AS project_id,
    d.file_id::text AS file_id,
    d.filename,
    d.status,
    d.reason
FROM documents d
WHERE d.org_id = $1::uuid
  AND d.file_id = $2::uuid
`

type DocumentByFileParams struct {
	OrgID  string
	FileID string
}

type DocumentByFileRow struct {
	ID        string
	ProjectID string
	FileID    string
	Filename  string
	Status    string
	Reason    string
}

func (q *Queries) DocumentByFile(ctx context.Context, arg DocumentByFileParams) (DocumentByFileRow, error) {
	row := q.db.QueryRow(ctx, documentByFile, arg.OrgID, arg.FileID)
	var i DocumentByFileRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FileID,
		&i.Filename,
		&i.Status,
		&i.Reason,
	)
	return i, err
}

const enqueueJob = `-- name: EnqueueJob :execrows
INSERT INTO jobs (org_id, id, document_id, kind, status, priority)
SELECT
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4,
    'queued',
    CASE WHEN $4 IN ('intake', 'jev_retry') THEN 100 ELSE 0 END
WHERE EXISTS (
    SELECT 1 FROM documents
    WHERE org_id = $1::uuid
      AND id = $3::uuid
)
`

type EnqueueJobParams struct {
	OrgID      string
	ID         string
	DocumentID string
	Kind       string
}

func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, enqueueJob,
		arg.OrgID,
		arg.ID,
		arg.DocumentID,
		arg.Kind,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueStage = `-- name: EnqueueStage :execrows
INSERT INTO jobs (org_id, id, document_id, kind, status, priority)
SELECT
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4,
    'queued',
    0
WHERE EXISTS (
    SELECT 1 FROM documents
    WHERE org_id = $1::uuid
      AND id = $3::uuid
)
ON CONFLICT (org_id, document_id, kind) DO NOTHING
`

type EnqueueStageParams struct {
	OrgID      string
	ID         string
	DocumentID string
	Kind       string
}

func (q *Queries) EnqueueStage(ctx context.Context, arg EnqueueStageParams) (int64, error) {
	result, err := q.db.Exec(ctx, enqueueStage,
		arg.OrgID,
		arg.ID,
		arg.DocumentID,
		arg.Kind,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireJobLease = `-- name: ExpireJobLease :execrows
UPDATE jobs
SET locked_until = now() - interval '1 second'
WHERE org_id = $1::uuid
  AND id = $2::uuid
  AND status = 'leased'
`

type ExpireJobLeaseParams struct {
	OrgID string
	ID    string
}

func (q *Queries) ExpireJobLease(ctx context.Context, arg ExpireJobLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, expireJobLease, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failExhaustedJobs = `-- name: FailExhaustedJobs :exec
UPDATE jobs
SET
    status = 'failed',
    last_error = CASE WHEN last_error = '' THEN 'attempts exhausted' ELSE last_error END,
    locked_until = NULL,
    lease_token = NULL
WHERE org_id = $1::uuid
  AND status = 'leased'
  AND locked_until < now()
  AND attempts >= max_attempts
`

func (q *Queries) FailExhaustedJobs(ctx context.Context, orgID string) error {
	_, err := q.db.Exec(ctx, failExhaustedJobs, orgID)
	return err
}

const failJob = `-- name: FailJob :execrows
UPDATE jobs
SET
    status = CASE WHEN attempts >= max_attempts THEN 'failed' ELSE 'queued' END,
    run_after = CASE
        WHEN attempts >= max_attempts THEN run_after
        ELSE now() + make_interval(secs => $1::double precision)
    END,
    last_error = $2,
    locked_until = NULL,
    lease_token = NULL
WHERE org_id = $3::uuid
  AND id = $4::uuid
  AND lease_token = $5::uuid
  AND status = 'leased'
`

type FailJobParams struct {
	BackoffSeconds float64
	LastError      string
	OrgID          string
	ID             string
	LeaseToken     string
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, failJob,
		arg.BackoffSeconds,
		arg.LastError,
		arg.OrgID,
		arg.ID,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findFileByHash = `-- name: FindFileByHash :one
SELECT id::text AS id, project_id::text AS project_id, sha256, byte_size, media_type
FROM files
WHERE org_id = $1::uuid
  AND project_id = $2::uuid
  AND sha256 = $3
`

type FindFileByHashParams struct {
	OrgID     string
	ProjectID string
	Sha256    []byte
}

type FindFileByHashRow struct {
	ID        string
	ProjectID string
	Sha256    []byte
	ByteSize  int64
	MediaType string
}

func (q *Queries) FindFileByHash(ctx context.Context, arg FindFileByHashParams) (FindFileByHashRow, error) {
	row := q.db.QueryRow(ctx, findFileByHash, arg.OrgID, arg.ProjectID, arg.Sha256)
	var i FindFileByHashRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Sha256,
		&i.ByteSize,
		&i.MediaType,
	)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id::text AS id
FROM users
WHERE org_id = $1::uuid
  AND email = $2
`

type FindUserByEmailParams struct {
	OrgID string
	Email string
}

func (q *Queries) FindUserByEmail(ctx context.Context, arg FindUserByEmailParams) (string, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, arg.OrgID, arg.Email)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getDocument = `-- name: GetDocument :one
SELECT
    d.id::text AS id,
    d.project_id::text AS project_id,
    d.file_id::text AS file_id,
    d.filename,
    d.status,
    COALESCE(d.document_number, '') AS document_number,
    COALESCE(d.revision, '') AS revision,
    d.reason
FROM documents d
WHERE d.org_id = $1::uuid
  AND d.id = $2::uuid
`

type GetDocumentParams struct {
	OrgID string
	ID    string
}

type GetDocumentRow struct {
	ID             string
	ProjectID      string
	FileID         string
	Filename       string
	Status         string
	DocumentNumber string
	Revision       string
	Reason         string
}

func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) (GetDocumentRow, error) {
	row := q.db.QueryRow(ctx, getDocument, arg.OrgID, arg.ID)
	var i GetDocumentRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FileID,
		&i.Filename,
		&i.Status,
		&i.DocumentNumber,
		&i.Revision,
		&i.Reason,
	)
	return i, err
}

const getFile = `-- name: GetFile :one
SELECT id::text AS id, project_id::text AS project_id, sha256, byte_size, media_type
FROM files
WHERE org_id = $1::uuid
  AND id = $2::uuid
`

type GetFileParams struct {
	OrgID string
	ID    string
}

type GetFileRow struct {
	ID        string
	ProjectID string
	Sha256    []byte
	ByteSize  int64
	MediaType string
}

func (q *Queries) GetFile(ctx context.Context, arg GetFileParams) (GetFileRow, error) {
	row := q.db.QueryRow(ctx, getFile, arg.OrgID, arg.ID)
	var i GetFileRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Sha256,
		&i.ByteSize,
		&i.MediaType,
	)
	return i, err
}

const getInvite = `-- name: GetInvite :one
SELECT id::text AS id, email
FROM invites
WHERE org_id = $1::uuid
  AND id = $2::uuid
`

type GetInviteParams struct {
	OrgID string
	ID    string
}

type GetInviteRow struct {
	ID    string
	Email string
}

func (q *Queries) GetInvite(ctx context.Context, arg GetInviteParams) (GetInviteRow, error) {
	row := q.db.QueryRow(ctx, getInvite, arg.OrgID, arg.ID)
	var i GetInviteRow
	err := row.Scan(&i.ID, &i.Email)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT
    id::text AS id,
    document_id::text AS document_id,
    kind,
    status,
    attempts,
    max_attempts,
    priority,
    COALESCE(last_error, '') AS last_error
FROM jobs
WHERE org_id = $1::uuid
  AND id = $2::uuid
`

type GetJobParams struct {
	OrgID string
	ID    string
}

type GetJobRow struct {
	ID          string
	DocumentID  string
	Kind        string
	Status      string
	Attempts    int32
	MaxAttempts int32
	Priority    int32
	LastError   string
}

func (q *Queries) GetJob(ctx context.Context, arg GetJobParams) (GetJobRow, error) {
	row := q.db.QueryRow(ctx, getJob, arg.OrgID, arg.ID)
	var i GetJobRow
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Kind,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.Priority,
		&i.LastError,
	)
	return i, err
}

const getPassage = `-- name: GetPassage :one
SELECT id::text AS id, document_id::text AS document_id, ordinal, body
FROM passages
WHERE org_id = $1::uuid
  AND id = $2::uuid
`

type GetPassageParams struct {
	OrgID string
	ID    string
}

type GetPassageRow struct {
	ID         string
	DocumentID string
	Ordinal    int32
	Body       string
}

func (q *Queries) GetPassage(ctx context.Context, arg GetPassageParams) (GetPassageRow, error) {
	row := q.db.QueryRow(ctx, getPassage, arg.OrgID, arg.ID)
	var i GetPassageRow
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Ordinal,
		&i.Body,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id::text AS id, name
FROM projects
WHERE org_id = $1::uuid
  AND id = $2::uuid
`

type GetProjectParams struct {
	OrgID string
	ID    string
}

type GetProjectRow struct {
	ID   string
	Name string
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (GetProjectRow, error) {
	row := q.db.QueryRow(ctx, getProject, arg.OrgID, arg.ID)
	var i GetProjectRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id::text AS id, user_id::text AS user_id
FROM sessions
WHERE org_id = $1::uuid
  AND id = $2::uuid
`

type GetSessionParams struct {
	OrgID string
	ID    string
}

type GetSessionRow struct {
	ID     string
	UserID string
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, arg.OrgID, arg.ID)
	var i GetSessionRow
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}

const getSupersession = `-- name: GetSupersession :one
SELECT prior_document_id::text AS prior_document_id
FROM supersessions
WHERE org_id = $1::uuid
  AND document_id = $2::uuid
`

type GetSupersessionParams struct {
	OrgID      string
	DocumentID string
}

func (q *Queries) GetSupersession(ctx context.Context, arg GetSupersessionParams) (string, error) {
	row := q.db.QueryRow(ctx, getSupersession, arg.OrgID, arg.DocumentID)
	var prior_document_id string
	err := row.Scan(&prior_document_id)
	return prior_document_id, err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (org_id, id, kind, document_id, payload)
VALUES (
    $1::uuid,
    $2,
    $3,
    $4::uuid,
    $5
)
`

type InsertEventParams struct {
	OrgID      string
	ID         int64
	Kind       string
	DocumentID pgtype.UUID
	Payload    string
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.OrgID,
		arg.ID,
		arg.Kind,
		arg.DocumentID,
		arg.Payload,
	)
	return err
}

const insertFile = `-- name: InsertFile :one
INSERT INTO files (org_id, id, project_id, sha256, byte_size, media_type)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4,
    $5,
    $6
)
ON CONFLICT (org_id, project_id, sha256) DO NOTHING
RETURNING id::text AS id
`

type InsertFileParams struct {
	OrgID     string
	ID        string
	ProjectID string
	Sha256    []byte
	ByteSize  int64
	MediaType string
}

func (q *Queries) InsertFile(ctx context.Context, arg InsertFileParams) (string, error) {
	row := q.db.QueryRow(ctx, insertFile,
		arg.OrgID,
		arg.ID,
		arg.ProjectID,
		arg.Sha256,
		arg.ByteSize,
		arg.MediaType,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertPassageSystem = `-- name: InsertPassageSystem :exec
INSERT INTO passage_systems (org_id, passage_id, system_id)
VALUES ($1::uuid, $2::uuid, $3)
ON CONFLICT (org_id, passage_id, system_id) DO NOTHING
`

type InsertPassageSystemParams struct {
	OrgID     string
	PassageID string
	SystemID  string
}

func (q *Queries) InsertPassageSystem(ctx context.Context, arg InsertPassageSystemParams) error {
	_, err := q.db.Exec(ctx, insertPassageSystem, arg.OrgID, arg.PassageID, arg.SystemID)
	return err
}

const jobByDocumentKind = `-- name: JobByDocumentKind :one
SELECT id::text AS id, document_id::text AS document_id, kind, status
FROM jobs
WHERE org_id = $1::uuid
  AND document_id = $2::uuid
  AND kind = $3
`

type JobByDocumentKindParams struct {
	OrgID      string
	DocumentID string
	Kind       string
}

type JobByDocumentKindRow struct {
	ID         string
	DocumentID string
	Kind       string
	Status     string
}

func (q *Queries) JobByDocumentKind(ctx context.Context, arg JobByDocumentKindParams) (JobByDocumentKindRow, error) {
	row := q.db.QueryRow(ctx, jobByDocumentKind, arg.OrgID, arg.DocumentID, arg.Kind)
	var i JobByDocumentKindRow
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Kind,
		&i.Status,
	)
	return i, err
}

const listContentHashes = `-- name: ListContentHashes :many
SELECT DISTINCT sha256
FROM files
ORDER BY sha256
`

func (q *Queries) ListContentHashes(ctx context.Context) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listContentHashes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var sha256 []byte
		if err := rows.Scan(&sha256); err != nil {
			return nil, err
		}
		items = append(items, sha256)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentPassages = `-- name: ListDocumentPassages :many
SELECT id::text AS id, ordinal, body
FROM passages
WHERE org_id = $1::uuid
  AND document_id = $2::uuid
ORDER BY ordinal
`

type ListDocumentPassagesParams struct {
	OrgID      string
	DocumentID string
}

type ListDocumentPassagesRow struct {
	ID      string
	Ordinal int32
	Body    string
}

func (q *Queries) ListDocumentPassages(ctx context.Context, arg ListDocumentPassagesParams) ([]ListDocumentPassagesRow, error) {
	rows, err := q.db.Query(ctx, listDocumentPassages, arg.OrgID, arg.DocumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentPassagesRow
	for rows.Next() {
		var i ListDocumentPassagesRow
		if err := rows.Scan(&i.ID, &i.Ordinal, &i.Body); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsAfter = `-- name: ListEventsAfter :many
SELECT
    id,
    kind,
    CAST(COALESCE(document_id::text, '') AS text) AS document_id,
    payload
FROM events
WHERE org_id = $1::uuid
  AND id > $2
ORDER BY id
LIMIT $3
`

type ListEventsAfterParams struct {
	OrgID    string
	AfterID  int64
	RowLimit int32
}

type ListEventsAfterRow struct {
	ID         int64
	Kind       string
	DocumentID string
	Payload    string
}

func (q *Queries) ListEventsAfter(ctx context.Context, arg ListEventsAfterParams) ([]ListEventsAfterRow, error) {
	rows, err := q.db.Query(ctx, listEventsAfter, arg.OrgID, arg.AfterID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsAfterRow
	for rows.Next() {
		var i ListEventsAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.DocumentID,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT id::text AS id, document_id::text AS document_id, kind, status
FROM jobs
WHERE org_id = $1::uuid
ORDER BY id
`

type ListJobsRow struct {
	ID         string
	DocumentID string
	Kind       string
	Status     string
}

func (q *Queries) ListJobs(ctx context.Context, orgID string) ([]ListJobsRow, error) {
	rows, err := q.db.Query(ctx, listJobs, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobsRow
	for rows.Next() {
		var i ListJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Kind,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPassageEvidence = `-- name: ListPassageEvidence :many
SELECT question_id, state
FROM passage_evidence
WHERE org_id = $1::uuid
  AND passage_id = $2::uuid
ORDER BY question_id
`

type ListPassageEvidenceParams struct {
	OrgID     string
	PassageID string
}

type ListPassageEvidenceRow struct {
	QuestionID string
	State      string
}

func (q *Queries) ListPassageEvidence(ctx context.Context, arg ListPassageEvidenceParams) ([]ListPassageEvidenceRow, error) {
	rows, err := q.db.Query(ctx, listPassageEvidence, arg.OrgID, arg.PassageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPassageEvidenceRow
	for rows.Next() {
		var i ListPassageEvidenceRow
		if err := rows.Scan(&i.QuestionID, &i.State); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPassageSystems = `-- name: ListPassageSystems :many
SELECT system_id
FROM passage_systems
WHERE org_id = $1::uuid
  AND passage_id = $2::uuid
ORDER BY system_id
`

type ListPassageSystemsParams struct {
	OrgID     string
	PassageID string
}

func (q *Queries) ListPassageSystems(ctx context.Context, arg ListPassageSystemsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listPassageSystems, arg.OrgID, arg.PassageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var system_id string
		if err := rows.Scan(&system_id); err != nil {
			return nil, err
		}
		items = append(items, system_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStream = `-- name: ListStream :many
SELECT
    d.id::text AS id,
    d.document_id::text AS document_id,
    d.field,
    COALESCE(d.value, '') AS value,
    d.band,
    d.decided_by
FROM decisions d
JOIN documents doc
    ON doc.org_id = d.org_id
   AND doc.id = d.document_id
WHERE d.org_id = $1::uuid
  AND doc.project_id = $2::uuid
ORDER BY d.id
`

type ListStreamParams struct {
	OrgID     string
	ProjectID string
}

type ListStreamRow struct {
	ID         string
	DocumentID string
	Field      string
	Value      string
	Band       string
	DecidedBy  string
}

func (q *Queries) ListStream(ctx context.Context, arg ListStreamParams) ([]ListStreamRow, error) {
	rows, err := q.db.Query(ctx, listStream, arg.OrgID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStreamRow
	for rows.Next() {
		var i ListStreamRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Field,
			&i.Value,
			&i.Band,
			&i.DecidedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockFileByHash = `-- name: LockFileByHash :one
SELECT id::text AS id, project_id::text AS project_id, sha256, byte_size, media_type
FROM files
WHERE org_id = $1::uuid
  AND project_id = $2::uuid
  AND sha256 = $3
FOR UPDATE
`

type LockFileByHashParams struct {
	OrgID     string
	ProjectID string
	Sha256    []byte
}

type LockFileByHashRow struct {
	ID        string
	ProjectID string
	Sha256    []byte
	ByteSize  int64
	MediaType string
}

func (q *Queries) LockFileByHash(ctx context.Context, arg LockFileByHashParams) (LockFileByHashRow, error) {
	row := q.db.QueryRow(ctx, lockFileByHash, arg.OrgID, arg.ProjectID, arg.Sha256)
	var i LockFileByHashRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Sha256,
		&i.ByteSize,
		&i.MediaType,
	)
	return i, err
}

const lockInviteByHash = `-- name: LockInviteByHash :one
SELECT
    org_id::text AS org_id,
    id::text AS id,
    email,
    role,
    expires_at,
    (consumed_at IS NOT NULL)::boolean AS consumed
FROM invites
WHERE token_hash = $1
FOR UPDATE
`

type LockInviteByHashRow struct {
	OrgID     string
	ID        string
	Email     string
	Role      string
	ExpiresAt time.Time
	Consumed  bool
}

func (q *Queries) LockInviteByHash(ctx context.Context, tokenHash []byte) (LockInviteByHashRow, error) {
	row := q.db.QueryRow(ctx, lockInviteByHash, tokenHash)
	var i LockInviteByHashRow
	err := row.Scan(
		&i.OrgID,
		&i.ID,
		&i.Email,
		&i.Role,
		&i.ExpiresAt,
		&i.Consumed,
	)
	return i, err
}

const lookupSession = `-- name: LookupSession :one
SELECT org_id::text AS org_id, user_id::text AS user_id, expires_at
FROM sessions
WHERE id = $1::uuid
`

type LookupSessionRow struct {
	OrgID     string
	UserID    string
	ExpiresAt time.Time
}

func (q *Queries) LookupSession(ctx context.Context, id string) (LookupSessionRow, error) {
	row := q.db.QueryRow(ctx, lookupSession, id)
	var i LookupSessionRow
	err := row.Scan(&i.OrgID, &i.UserID, &i.ExpiresAt)
	return i, err
}

const markInviteConsumed = `-- name: MarkInviteConsumed :execrows
UPDATE invites
SET consumed_at = now()
WHERE org_id = $1::uuid
  AND id = $2::uuid
  AND consumed_at IS NULL
`

type MarkInviteConsumedParams struct {
	OrgID string
	ID    string
}

func (q *Queries) MarkInviteConsumed(ctx context.Context, arg MarkInviteConsumedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markInviteConsumed, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const membershipExists = `-- name: MembershipExists :one
SELECT true AS member
FROM memberships
WHERE org_id = $1::uuid
  AND user_id = $2::uuid
`

type MembershipExistsParams struct {
	OrgID  string
	UserID string
}

func (q *Queries) MembershipExists(ctx context.Context, arg MembershipExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, membershipExists, arg.OrgID, arg.UserID)
	var member bool
	err := row.Scan(&member)
	return member, err
}

const membershipRole = `-- name: MembershipRole :one
SELECT role
FROM memberships
WHERE org_id = $1::uuid
  AND user_id = $2::uuid
`

type MembershipRoleParams struct {
	OrgID  string
	UserID string
}

func (q *Queries) MembershipRole(ctx context.Context, arg MembershipRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, membershipRole, arg.OrgID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const nextEventID = `-- name: NextEventID :one
INSERT INTO event_counters (org_id, last_id)
VALUES ($1::uuid, 1)
ON CONFLICT (org_id) DO UPDATE
SET last_id = event_counters.last_id + 1
RETURNING last_id
`

func (q *Queries) NextEventID(ctx context.Context, orgID string) (int64, error) {
	row := q.db.QueryRow(ctx, nextEventID, orgID)
	var last_id int64
	err := row.Scan(&last_id)
	return last_id, err
}

const orgBacklog = `-- name: OrgBacklog :many
SELECT kind,
       count(*)::bigint AS queued,
       floor(extract(epoch FROM now() - min(created_at)) * 1000)::bigint AS oldest_ms
FROM jobs
WHERE org_id = $1::uuid
  AND status IN ('queued', 'leased')
GROUP BY kind
ORDER BY kind
`

type OrgBacklogRow struct {
	Kind     string
	Queued   int64
	OldestMs int64
}

func (q *Queries) OrgBacklog(ctx context.Context, orgID string) ([]OrgBacklogRow, error) {
	rows, err := q.db.Query(ctx, orgBacklog, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrgBacklogRow
	for rows.Next() {
		var i OrgBacklogRow
		if err := rows.Scan(&i.Kind, &i.Queued, &i.OldestMs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPassages = `-- name: SearchPassages :many
SELECT p.id::text AS id, p.document_id::text AS document_id, p.ordinal, p.body
FROM passages p
JOIN documents d
    ON d.org_id = p.org_id
   AND d.id = p.document_id
WHERE p.org_id = $1::uuid
  AND d.project_id = $2::uuid
  AND p.body_tsv @@ websearch_to_tsquery('english', $3)
ORDER BY ts_rank(p.body_tsv, websearch_to_tsquery('english', $3)) DESC, p.ordinal
LIMIT $4
`

type SearchPassagesParams struct {
	OrgID     string
	ProjectID string
	Query     string
	RowLimit  int32
}

type SearchPassagesRow struct {
	ID         string
	DocumentID string
	Ordinal    int32
	Body       string
}

func (q *Queries) SearchPassages(ctx context.Context, arg SearchPassagesParams) ([]SearchPassagesRow, error) {
	rows, err := q.db.Query(ctx, searchPassages,
		arg.OrgID,
		arg.ProjectID,
		arg.Query,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPassagesRow
	for rows.Next() {
		var i SearchPassagesRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Ordinal,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const supersedeDocument = `-- name: SupersedeDocument :execrows
INSERT INTO supersessions (org_id, document_id, prior_document_id)
SELECT $1::uuid, $2::uuid, $3::uuid
WHERE EXISTS (
    SELECT 1 FROM documents
    WHERE org_id = $1::uuid
      AND id = $2::uuid
) AND EXISTS (
    SELECT 1 FROM documents
    WHERE org_id = $1::uuid
      AND id = $3::uuid
) AND $2::uuid <> $3::uuid
`

type SupersedeDocumentParams struct {
	OrgID           string
	DocumentID      string
	PriorDocumentID string
}

func (q *Queries) SupersedeDocument(ctx context.Context, arg SupersedeDocumentParams) (int64, error) {
	result, err := q.db.Exec(ctx, supersedeDocument, arg.OrgID, arg.DocumentID, arg.PriorDocumentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDocumentStatus = `-- name: UpdateDocumentStatus :execrows
UPDATE documents
SET status = $1
WHERE org_id = $2::uuid
  AND id = $3::uuid
`

type UpdateDocumentStatusParams struct {
	Status string
	OrgID  string
	ID     string
}

func (q *Queries) UpdateDocumentStatus(ctx context.Context, arg UpdateDocumentStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDocumentStatus, arg.Status, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertPassageEvidence = `-- name: UpsertPassageEvidence :exec
INSERT INTO passage_evidence (org_id, passage_id, question_id, state)
VALUES (
    $1::uuid,
    $2::uuid,
    $3,
    $4
)
ON CONFLICT (org_id, passage_id, question_id) DO UPDATE
SET state = EXCLUDED.state
`

type UpsertPassageEvidenceParams struct {
	OrgID      string
	PassageID  string
	QuestionID string
	State      string
}

func (q *Queries) UpsertPassageEvidence(ctx context.Context, arg UpsertPassageEvidenceParams) error {
	_, err := q.db.Exec(ctx, upsertPassageEvidence,
		arg.OrgID,
		arg.PassageID,
		arg.QuestionID,
		arg.State,
	)
	return err
}
