// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"time"
)

const addPassage = `-- name: AddPassage :exec
INSERT INTO passages (org_id, id, document_id, ordinal, body)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4,
    $5
)
`

type AddPassageParams struct {
	OrgID      string
	ID         string
	DocumentID string
	Ordinal    int32
	Body       string
}

func (q *Queries) AddPassage(ctx context.Context, arg AddPassageParams) error {
	_, err := q.db.Exec(ctx, addPassage,
		arg.OrgID,
		arg.ID,
		arg.DocumentID,
		arg.Ordinal,
		arg.Body,
	)
	return err
}

const createDecision = `-- name: CreateDecision :exec
INSERT INTO decisions (org_id, id, document_id, field, value, band, decided_by)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4,
    $5,
    $6,
    $7
)
`

type CreateDecisionParams struct {
	OrgID      string
	ID         string
	DocumentID string
	Field      string
	Value      *string
	Band       string
	DecidedBy  string
}

func (q *Queries) CreateDecision(ctx context.Context, arg CreateDecisionParams) error {
	_, err := q.db.Exec(ctx, createDecision,
		arg.OrgID,
		arg.ID,
		arg.DocumentID,
		arg.Field,
		arg.Value,
		arg.Band,
		arg.DecidedBy,
	)
	return err
}

const createDocument = `-- name: CreateDocument :exec
INSERT INTO documents (
    org_id, id, project_id, file_id, filename, status, document_number, revision
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4::uuid,
    $5,
    $6,
    $7,
    $8
)
`

type CreateDocumentParams struct {
	OrgID          string
	ID             string
	ProjectID      string
	FileID         string
	Filename       string
	Status         string
	DocumentNumber *string
	Revision       *string
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) error {
	_, err := q.db.Exec(ctx, createDocument,
		arg.OrgID,
		arg.ID,
		arg.ProjectID,
		arg.FileID,
		arg.Filename,
		arg.Status,
		arg.DocumentNumber,
		arg.Revision,
	)
	return err
}

const createFile = `-- name: CreateFile :exec
INSERT INTO files (org_id, id, project_id, sha256, byte_size, media_type)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4,
    $5,
    $6
)
`

type CreateFileParams struct {
	OrgID     string
	ID        string
	ProjectID string
	Sha256    []byte
	ByteSize  int64
	MediaType string
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) error {
	_, err := q.db.Exec(ctx, createFile,
		arg.OrgID,
		arg.ID,
		arg.ProjectID,
		arg.Sha256,
		arg.ByteSize,
		arg.MediaType,
	)
	return err
}

const createInvite = `-- name: CreateInvite :exec
INSERT INTO invites (org_id, id, email, token_hash, role, expires_at)
VALUES (
    $1::uuid,
    $2::uuid,
    $3,
    $4,
    $5,
    $6
)
`

type CreateInviteParams struct {
	OrgID     string
	ID        string
	Email     string
	TokenHash []byte
	Role      string
	ExpiresAt time.Time
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) error {
	_, err := q.db.Exec(ctx, createInvite,
		arg.OrgID,
		arg.ID,
		arg.Email,
		arg.TokenHash,
		arg.Role,
		arg.ExpiresAt,
	)
	return err
}

const createMembership = `-- name: CreateMembership :exec
INSERT INTO memberships (org_id, user_id, role)
VALUES ($1::uuid, $2::uuid, $3)
ON CONFLICT (org_id, user_id) DO NOTHING
`

type CreateMembershipParams struct {
	OrgID  string
	UserID string
	Role   string
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) error {
	_, err := q.db.Exec(ctx, createMembership, arg.OrgID, arg.UserID, arg.Role)
	return err
}

const createOrg = `-- name: CreateOrg :exec
INSERT INTO orgs (id, name)
VALUES ($1::uuid, $2)
`

type CreateOrgParams struct {
	ID   string
	Name string
}

func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) error {
	_, err := q.db.Exec(ctx, createOrg, arg.ID, arg.Name)
	return err
}

const createProject = `-- name: CreateProject :exec
INSERT INTO projects (org_id, id, name)
VALUES ($1::uuid, $2::uuid, $3)
`

type CreateProjectParams struct {
	OrgID string
	ID    string
	Name  string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.Exec(ctx, createProject, arg.OrgID, arg.ID, arg.Name)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (org_id, id, user_id)
VALUES ($1::uuid, $2::uuid, $3::uuid)
`

type CreateSessionParams struct {
	OrgID  string
	ID     string
	UserID string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.OrgID, arg.ID, arg.UserID)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (org_id, id, email)
VALUES ($1::uuid, $2::uuid, $3)
`

type CreateUserParams struct {
	OrgID string
	ID    string
	Email string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.OrgID, arg.ID, arg.Email)
	return err
}

const deleteOrg = `-- name: DeleteOrg :exec
DELETE FROM orgs
WHERE id = $1::uuid
`

func (q *Queries) DeleteOrg(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteOrg, id)
	return err
}

const enqueueJob = `-- name: EnqueueJob :execrows
INSERT INTO jobs (org_id, id, document_id, kind, status)
SELECT $1::uuid, $2::uuid, $3::uuid, $4, 'queued'
WHERE EXISTS (
    SELECT 1 FROM documents
    WHERE org_id = $1::uuid
      AND id = $3::uuid
)
`

type EnqueueJobParams struct {
	OrgID      string
	ID         string
	DocumentID string
	Kind       string
}

func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, enqueueJob,
		arg.OrgID,
		arg.ID,
		arg.DocumentID,
		arg.Kind,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findFileByHash = `-- name: FindFileByHash :one
SELECT id::text AS id, project_id::text AS project_id, sha256, byte_size, media_type
FROM files
WHERE org_id = $1::uuid
  AND project_id = $2::uuid
  AND sha256 = $3
`

type FindFileByHashParams struct {
	OrgID     string
	ProjectID string
	Sha256    []byte
}

type FindFileByHashRow struct {
	ID        string
	ProjectID string
	Sha256    []byte
	ByteSize  int64
	MediaType string
}

func (q *Queries) FindFileByHash(ctx context.Context, arg FindFileByHashParams) (FindFileByHashRow, error) {
	row := q.db.QueryRow(ctx, findFileByHash, arg.OrgID, arg.ProjectID, arg.Sha256)
	var i FindFileByHashRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Sha256,
		&i.ByteSize,
		&i.MediaType,
	)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id::text AS id
FROM users
WHERE org_id = $1::uuid
  AND email = $2
`

type FindUserByEmailParams struct {
	OrgID string
	Email string
}

func (q *Queries) FindUserByEmail(ctx context.Context, arg FindUserByEmailParams) (string, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, arg.OrgID, arg.Email)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getDocument = `-- name: GetDocument :one
SELECT
    d.id::text AS id,
    d.project_id::text AS project_id,
    d.file_id::text AS file_id,
    d.filename,
    d.status,
    COALESCE(d.document_number, '') AS document_number,
    COALESCE(d.revision, '') AS revision
FROM documents d
WHERE d.org_id = $1::uuid
  AND d.id = $2::uuid
`

type GetDocumentParams struct {
	OrgID string
	ID    string
}

type GetDocumentRow struct {
	ID             string
	ProjectID      string
	FileID         string
	Filename       string
	Status         string
	DocumentNumber string
	Revision       string
}

func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) (GetDocumentRow, error) {
	row := q.db.QueryRow(ctx, getDocument, arg.OrgID, arg.ID)
	var i GetDocumentRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FileID,
		&i.Filename,
		&i.Status,
		&i.DocumentNumber,
		&i.Revision,
	)
	return i, err
}

const getFile = `-- name: GetFile :one
SELECT id::text AS id, project_id::text AS project_id, sha256, byte_size, media_type
FROM files
WHERE org_id = $1::uuid
  AND id = $2::uuid
`

type GetFileParams struct {
	OrgID string
	ID    string
}

type GetFileRow struct {
	ID        string
	ProjectID string
	Sha256    []byte
	ByteSize  int64
	MediaType string
}

func (q *Queries) GetFile(ctx context.Context, arg GetFileParams) (GetFileRow, error) {
	row := q.db.QueryRow(ctx, getFile, arg.OrgID, arg.ID)
	var i GetFileRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Sha256,
		&i.ByteSize,
		&i.MediaType,
	)
	return i, err
}

const getInvite = `-- name: GetInvite :one
SELECT id::text AS id, email
FROM invites
WHERE org_id = $1::uuid
  AND id = $2::uuid
`

type GetInviteParams struct {
	OrgID string
	ID    string
}

type GetInviteRow struct {
	ID    string
	Email string
}

func (q *Queries) GetInvite(ctx context.Context, arg GetInviteParams) (GetInviteRow, error) {
	row := q.db.QueryRow(ctx, getInvite, arg.OrgID, arg.ID)
	var i GetInviteRow
	err := row.Scan(&i.ID, &i.Email)
	return i, err
}

const getPassage = `-- name: GetPassage :one
SELECT id::text AS id, document_id::text AS document_id, ordinal, body
FROM passages
WHERE org_id = $1::uuid
  AND id = $2::uuid
`

type GetPassageParams struct {
	OrgID string
	ID    string
}

type GetPassageRow struct {
	ID         string
	DocumentID string
	Ordinal    int32
	Body       string
}

func (q *Queries) GetPassage(ctx context.Context, arg GetPassageParams) (GetPassageRow, error) {
	row := q.db.QueryRow(ctx, getPassage, arg.OrgID, arg.ID)
	var i GetPassageRow
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Ordinal,
		&i.Body,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id::text AS id, name
FROM projects
WHERE org_id = $1::uuid
  AND id = $2::uuid
`

type GetProjectParams struct {
	OrgID string
	ID    string
}

type GetProjectRow struct {
	ID   string
	Name string
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (GetProjectRow, error) {
	row := q.db.QueryRow(ctx, getProject, arg.OrgID, arg.ID)
	var i GetProjectRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id::text AS id, user_id::text AS user_id
FROM sessions
WHERE org_id = $1::uuid
  AND id = $2::uuid
`

type GetSessionParams struct {
	OrgID string
	ID    string
}

type GetSessionRow struct {
	ID     string
	UserID string
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, arg.OrgID, arg.ID)
	var i GetSessionRow
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}

const getSupersession = `-- name: GetSupersession :one
SELECT prior_document_id::text AS prior_document_id
FROM supersessions
WHERE org_id = $1::uuid
  AND document_id = $2::uuid
`

type GetSupersessionParams struct {
	OrgID      string
	DocumentID string
}

func (q *Queries) GetSupersession(ctx context.Context, arg GetSupersessionParams) (string, error) {
	row := q.db.QueryRow(ctx, getSupersession, arg.OrgID, arg.DocumentID)
	var prior_document_id string
	err := row.Scan(&prior_document_id)
	return prior_document_id, err
}

const listJobs = `-- name: ListJobs :many
SELECT id::text AS id, document_id::text AS document_id, kind, status
FROM jobs
WHERE org_id = $1::uuid
ORDER BY id
`

type ListJobsRow struct {
	ID         string
	DocumentID string
	Kind       string
	Status     string
}

func (q *Queries) ListJobs(ctx context.Context, orgID string) ([]ListJobsRow, error) {
	rows, err := q.db.Query(ctx, listJobs, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobsRow
	for rows.Next() {
		var i ListJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Kind,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStream = `-- name: ListStream :many
SELECT
    d.id::text AS id,
    d.document_id::text AS document_id,
    d.field,
    COALESCE(d.value, '') AS value,
    d.band,
    d.decided_by
FROM decisions d
JOIN documents doc
    ON doc.org_id = d.org_id
   AND doc.id = d.document_id
WHERE d.org_id = $1::uuid
  AND doc.project_id = $2::uuid
ORDER BY d.id
`

type ListStreamParams struct {
	OrgID     string
	ProjectID string
}

type ListStreamRow struct {
	ID         string
	DocumentID string
	Field      string
	Value      string
	Band       string
	DecidedBy  string
}

func (q *Queries) ListStream(ctx context.Context, arg ListStreamParams) ([]ListStreamRow, error) {
	rows, err := q.db.Query(ctx, listStream, arg.OrgID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStreamRow
	for rows.Next() {
		var i ListStreamRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Field,
			&i.Value,
			&i.Band,
			&i.DecidedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockInviteByHash = `-- name: LockInviteByHash :one
SELECT
    org_id::text AS org_id,
    id::text AS id,
    email,
    role,
    expires_at,
    (consumed_at IS NOT NULL)::boolean AS consumed
FROM invites
WHERE token_hash = $1
FOR UPDATE
`

type LockInviteByHashRow struct {
	OrgID     string
	ID        string
	Email     string
	Role      string
	ExpiresAt time.Time
	Consumed  bool
}

func (q *Queries) LockInviteByHash(ctx context.Context, tokenHash []byte) (LockInviteByHashRow, error) {
	row := q.db.QueryRow(ctx, lockInviteByHash, tokenHash)
	var i LockInviteByHashRow
	err := row.Scan(
		&i.OrgID,
		&i.ID,
		&i.Email,
		&i.Role,
		&i.ExpiresAt,
		&i.Consumed,
	)
	return i, err
}

const lookupSession = `-- name: LookupSession :one
SELECT org_id::text AS org_id, user_id::text AS user_id, expires_at
FROM sessions
WHERE id = $1::uuid
`

type LookupSessionRow struct {
	OrgID     string
	UserID    string
	ExpiresAt time.Time
}

func (q *Queries) LookupSession(ctx context.Context, id string) (LookupSessionRow, error) {
	row := q.db.QueryRow(ctx, lookupSession, id)
	var i LookupSessionRow
	err := row.Scan(&i.OrgID, &i.UserID, &i.ExpiresAt)
	return i, err
}

const markInviteConsumed = `-- name: MarkInviteConsumed :execrows
UPDATE invites
SET consumed_at = now()
WHERE org_id = $1::uuid
  AND id = $2::uuid
  AND consumed_at IS NULL
`

type MarkInviteConsumedParams struct {
	OrgID string
	ID    string
}

func (q *Queries) MarkInviteConsumed(ctx context.Context, arg MarkInviteConsumedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markInviteConsumed, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const membershipExists = `-- name: MembershipExists :one
SELECT true AS member
FROM memberships
WHERE org_id = $1::uuid
  AND user_id = $2::uuid
`

type MembershipExistsParams struct {
	OrgID  string
	UserID string
}

func (q *Queries) MembershipExists(ctx context.Context, arg MembershipExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, membershipExists, arg.OrgID, arg.UserID)
	var member bool
	err := row.Scan(&member)
	return member, err
}

const supersedeDocument = `-- name: SupersedeDocument :execrows
INSERT INTO supersessions (org_id, document_id, prior_document_id)
SELECT $1::uuid, $2::uuid, $3::uuid
WHERE EXISTS (
    SELECT 1 FROM documents
    WHERE org_id = $1::uuid
      AND id = $2::uuid
) AND EXISTS (
    SELECT 1 FROM documents
    WHERE org_id = $1::uuid
      AND id = $3::uuid
) AND $2::uuid <> $3::uuid
`

type SupersedeDocumentParams struct {
	OrgID           string
	DocumentID      string
	PriorDocumentID string
}

func (q *Queries) SupersedeDocument(ctx context.Context, arg SupersedeDocumentParams) (int64, error) {
	result, err := q.db.Exec(ctx, supersedeDocument, arg.OrgID, arg.DocumentID, arg.PriorDocumentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDocumentStatus = `-- name: UpdateDocumentStatus :execrows
UPDATE documents
SET status = $1
WHERE org_id = $2::uuid
  AND id = $3::uuid
`

type UpdateDocumentStatusParams struct {
	Status string
	OrgID  string
	ID     string
}

func (q *Queries) UpdateDocumentStatus(ctx context.Context, arg UpdateDocumentStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDocumentStatus, arg.Status, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
