// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: restore.sql

package db

import (
	"context"
)

const crossOrgRows = `-- name: CrossOrgRows :many
SELECT 'events.document_id' AS reference, count(*)::bigint AS rows
FROM events e
WHERE e.document_id IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.org_id = e.org_id AND d.id = e.document_id)
UNION ALL
SELECT 'documents.project_id', count(*)::bigint
FROM documents d
WHERE NOT EXISTS (SELECT 1 FROM projects p WHERE p.org_id = d.org_id AND p.id = d.project_id)
UNION ALL
SELECT 'documents.file_id', count(*)::bigint
FROM documents d
WHERE NOT EXISTS (SELECT 1 FROM files f WHERE f.org_id = d.org_id AND f.id = d.file_id)
UNION ALL
SELECT 'decisions.document_id', count(*)::bigint
FROM decisions c
WHERE NOT EXISTS (SELECT 1 FROM documents d WHERE d.org_id = c.org_id AND d.id = c.document_id)
UNION ALL
SELECT 'sessions.user_id', count(*)::bigint
FROM sessions s
WHERE NOT EXISTS (SELECT 1 FROM users u WHERE u.org_id = s.org_id AND u.id = s.user_id)
UNION ALL
SELECT 'memberships.user_id', count(*)::bigint
FROM memberships m
WHERE NOT EXISTS (SELECT 1 FROM users u WHERE u.org_id = m.org_id AND u.id = m.user_id)
`

type CrossOrgRowsRow struct {
	Reference string
	Rows      int64
}

// Rows whose parent is not in the same org. Composite keys make most of
// these impossible while the constraints hold; the checks prove the restored
// data, not the schema. events.document_id has no foreign key at all.
func (q *Queries) CrossOrgRows(ctx context.Context) ([]CrossOrgRowsRow, error) {
	rows, err := q.db.Query(ctx, crossOrgRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrossOrgRowsRow
	for rows.Next() {
		var i CrossOrgRowsRow
		if err := rows.Scan(&i.Reference, &i.Rows); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const foreignKeyState = `-- name: ForeignKeyState :one
SELECT count(*)::bigint AS total,
       count(*) FILTER (WHERE NOT convalidated)::bigint AS unvalidated
FROM pg_catalog.pg_constraint
WHERE contype = 'f'
  AND connamespace = 'public'::regnamespace
`

type ForeignKeyStateRow struct {
	Total       int64
	Unvalidated int64
}

func (q *Queries) ForeignKeyState(ctx context.Context) (ForeignKeyStateRow, error) {
	row := q.db.QueryRow(ctx, foreignKeyState)
	var i ForeignKeyStateRow
	err := row.Scan(&i.Total, &i.Unvalidated)
	return i, err
}

const orgCounts = `-- name: OrgCounts :many

SELECT o.id::text AS org_id,
       (SELECT count(*) FROM users u WHERE u.org_id = o.id)::bigint AS users,
       (SELECT count(*) FROM memberships m WHERE m.org_id = o.id)::bigint AS memberships,
       (SELECT count(*) FROM projects p WHERE p.org_id = o.id)::bigint AS projects,
       (SELECT count(*) FROM files f WHERE f.org_id = o.id)::bigint AS files,
       (SELECT count(*) FROM documents d WHERE d.org_id = o.id)::bigint AS documents,
       (SELECT count(*) FROM decisions c WHERE c.org_id = o.id)::bigint AS decisions,
       (SELECT count(*) FROM passages s WHERE s.org_id = o.id)::bigint AS passages,
       (SELECT count(*) FROM events e WHERE e.org_id = o.id)::bigint AS events
FROM orgs o
ORDER BY o.id
`

type OrgCountsRow struct {
	OrgID       string
	Users       int64
	Memberships int64
	Projects    int64
	Files       int64
	Documents   int64
	Decisions   int64
	Passages    int64
	Events      int64
}

// Restore rehearsal facts. Counts and catalog state only; no row content.
func (q *Queries) OrgCounts(ctx context.Context) ([]OrgCountsRow, error) {
	rows, err := q.db.Query(ctx, orgCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrgCountsRow
	for rows.Next() {
		var i OrgCountsRow
		if err := rows.Scan(
			&i.OrgID,
			&i.Users,
			&i.Memberships,
			&i.Projects,
			&i.Files,
			&i.Documents,
			&i.Decisions,
			&i.Passages,
			&i.Events,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
