// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: views.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDocumentView = `-- name: GetDocumentView :one
SELECT
    d.id::text AS id,
    d.project_id::text AS project_id,
    d.filename,
    d.status,
    d.reason,
    COALESCE(d.document_number, '') AS document_number,
    COALESCE(d.revision, '') AS revision,
    COALESCE(s.prior_document_id::text, '')::text AS supersedes_id,
    d.created_at
FROM documents d
LEFT JOIN supersessions s
    ON s.org_id = d.org_id
   AND s.document_id = d.id
WHERE d.org_id = $1::uuid
  AND d.id = $2::uuid
`

type GetDocumentViewParams struct {
	OrgID string
	ID    string
}

type GetDocumentViewRow struct {
	ID             string
	ProjectID      string
	Filename       string
	Status         string
	Reason         string
	DocumentNumber string
	Revision       string
	SupersedesID   string
	CreatedAt      time.Time
}

func (q *Queries) GetDocumentView(ctx context.Context, arg GetDocumentViewParams) (GetDocumentViewRow, error) {
	row := q.db.QueryRow(ctx, getDocumentView, arg.OrgID, arg.ID)
	var i GetDocumentViewRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Filename,
		&i.Status,
		&i.Reason,
		&i.DocumentNumber,
		&i.Revision,
		&i.SupersedesID,
		&i.CreatedAt,
	)
	return i, err
}

const latestEventID = `-- name: LatestEventID :one
SELECT COALESCE(
    (SELECT last_id FROM event_counters WHERE org_id = $1::uuid),
    0
)::bigint AS id
`

func (q *Queries) LatestEventID(ctx context.Context, orgID string) (int64, error) {
	row := q.db.QueryRow(ctx, latestEventID, orgID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listOrgProjects = `-- name: ListOrgProjects :many
SELECT id::text AS id, name
FROM projects
WHERE org_id = $1::uuid
ORDER BY created_at DESC, id
`

type ListOrgProjectsRow struct {
	ID   string
	Name string
}

func (q *Queries) ListOrgProjects(ctx context.Context, orgID string) ([]ListOrgProjectsRow, error) {
	rows, err := q.db.Query(ctx, listOrgProjects, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgProjectsRow
	for rows.Next() {
		var i ListOrgProjectsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingIntake = `-- name: ListPendingIntake :many
SELECT j.org_id::text AS org_id, j.document_id::text AS document_id
FROM jobs j
JOIN documents d
    ON d.org_id = j.org_id
   AND d.id = j.document_id
WHERE j.kind = 'intake'
  AND j.status = 'queued'
  AND d.status = 'pending'
ORDER BY j.created_at
LIMIT $1::int
`

type ListPendingIntakeRow struct {
	OrgID      string
	DocumentID string
}

// Every org's intake that has not been filed. Startup resumes these; the
// caller then works inside each row's org.
func (q *Queries) ListPendingIntake(ctx context.Context, rowLimit int32) ([]ListPendingIntakeRow, error) {
	rows, err := q.db.Query(ctx, listPendingIntake, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingIntakeRow
	for rows.Next() {
		var i ListPendingIntakeRow
		if err := rows.Scan(&i.OrgID, &i.DocumentID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectDecisionViews = `-- name: ListProjectDecisionViews :many
SELECT
    dc.document_id::text AS document_id,
    dc.field,
    COALESCE(dc.value, '') AS value,
    dc.band,
    dc.decided_by,
    COALESCE(dc.question_version, '') AS question_version,
    dc.confidence
FROM decisions dc
JOIN documents d
    ON d.org_id = dc.org_id
   AND d.id = dc.document_id
WHERE dc.org_id = $1::uuid
  AND d.project_id = $2::uuid
ORDER BY dc.document_id, dc.field
`

type ListProjectDecisionViewsParams struct {
	OrgID     string
	ProjectID string
}

type ListProjectDecisionViewsRow struct {
	DocumentID      string
	Field           string
	Value           string
	Band            string
	DecidedBy       string
	QuestionVersion string
	Confidence      pgtype.Float8
}

func (q *Queries) ListProjectDecisionViews(ctx context.Context, arg ListProjectDecisionViewsParams) ([]ListProjectDecisionViewsRow, error) {
	rows, err := q.db.Query(ctx, listProjectDecisionViews, arg.OrgID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectDecisionViewsRow
	for rows.Next() {
		var i ListProjectDecisionViewsRow
		if err := rows.Scan(
			&i.DocumentID,
			&i.Field,
			&i.Value,
			&i.Band,
			&i.DecidedBy,
			&i.QuestionVersion,
			&i.Confidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectDocumentViews = `-- name: ListProjectDocumentViews :many
SELECT
    d.id::text AS id,
    d.filename,
    d.status,
    d.reason,
    COALESCE(d.document_number, '') AS document_number,
    COALESCE(d.revision, '') AS revision,
    COALESCE(s.prior_document_id::text, '')::text AS supersedes_id,
    d.created_at
FROM documents d
LEFT JOIN supersessions s
    ON s.org_id = d.org_id
   AND s.document_id = d.id
WHERE d.org_id = $1::uuid
  AND d.project_id = $2::uuid
ORDER BY d.created_at DESC, d.id
`

type ListProjectDocumentViewsParams struct {
	OrgID     string
	ProjectID string
}

type ListProjectDocumentViewsRow struct {
	ID             string
	Filename       string
	Status         string
	Reason         string
	DocumentNumber string
	Revision       string
	SupersedesID   string
	CreatedAt      time.Time
}

func (q *Queries) ListProjectDocumentViews(ctx context.Context, arg ListProjectDocumentViewsParams) ([]ListProjectDocumentViewsRow, error) {
	rows, err := q.db.Query(ctx, listProjectDocumentViews, arg.OrgID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectDocumentViewsRow
	for rows.Next() {
		var i ListProjectDocumentViewsRow
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.Status,
			&i.Reason,
			&i.DocumentNumber,
			&i.Revision,
			&i.SupersedesID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPendingNotFiled = `-- name: MarkPendingNotFiled :execrows
UPDATE documents
SET status = 'not_filed', reason = $1
WHERE org_id = $2::uuid
  AND id = $3::uuid
  AND status = 'pending'
`

type MarkPendingNotFiledParams struct {
	Reason string
	OrgID  string
	ID     string
}

func (q *Queries) MarkPendingNotFiled(ctx context.Context, arg MarkPendingNotFiledParams) (int64, error) {
	result, err := q.db.Exec(ctx, markPendingNotFiled, arg.Reason, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
